### ISSUE TITLE
Issue connecting to Kinesalite despite existing stream?

### ISSUE THREAD

**Issue by GoldFlsh** [lifion/lifion-kinesis#336]
I am attempting to build a jest test around Kinesalite. We are using lifion-kinesis to connect to the AWS Kinesis streams in AWS, but for purposes of the component test want to use Kinesalite to isolate the program under test from its infrastructure. 

I didn't want to have to modify the program, and figured providing the `localhost` endpoint in the configuration would work ok...and it seems to recognize it in the `ensureStreamExists` function but when `kinesis.startConsumer();` is called it fails with the below error: 

Seems like a bug for it to be recognized but fail anyway. 
 
```
stream.js:143 (ensureStreamExists) Verifying the "local-kinesis-component-test" stream exists and it's active…
stream.js:161 (ensureStreamExists) The stream exists and it's active.
consumer.ts:34 (xxx) ResourceNotFoundException: Stream local-kinesis-component-test under account 000000000000 not found.
      at Request.extractError (/node_modules/lifion-kinesis/node_modules/aws-sdk/lib/protocol/json.js:51:27)
        at Request.callListeners (/node_modules/lifion-kinesis/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
        at Request.emit (/node_modules/lifion-kinesis/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
        at Request.emit (/node_modules/lifion-kinesis/node_modules/aws-sdk/lib/request.js:683:14)
        at Request.transition (/node_modules/lifion-kinesis/node_modules/aws-sdk/lib/request.js:22:10)
        at AcceptorStateMachine.runTo (/node_modules/lifion-kinesis/node_modules/aws-sdk/lib/state_machine.js:14:12)
        at /node_modules/lifion-kinesis/node_modules/aws-sdk/lib/state_machine.js:26:10
        at Request.<anonymous> (/node_modules/lifion-kinesis/node_modules/aws-sdk/lib/request.js:38:9)
        at Request.<anonymous> (/node_modules/lifion-kinesis/node_modules/aws-sdk/lib/request.js:685:12)
        at Request.callListeners (/node_modules/lifion-kinesis/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
      message: 'Stream local-kinesis-component-test under account 000000000000 not found.',
      code: 'ResourceNotFoundException',
      time: 2020-05-25T17:48:38.164Z,
      requestId: 'f694e540-9eaf-11ea-b2d8-8f0dd26471d6',
      statusCode: 400,
      retryable: false,
      retryDelay: 29.977332596696904
```

**Comment by GoldFlsh** [comment]
Sorry, looks like this was due to the fact that I was expecting tags on my kinesalite, that I wasn't setting up. I deleted that requirement and now it's able to find it. My bad. 

Maybe a specific error stating the configuration doesn't match the stream with that name in that case? Anyway, I will close this issue 👍
