### ISSUE TITLE
storeShardCheckpoint not catching ConditionalCheckFailedException

### ISSUE THREAD

**Issue by dselman** [lifion/lifion-kinesis#384]
We are seeing logs like this every 10 seconds or so:

```
ConditionalCheckFailedException: The conditional request failed
at Request.extractError (/app/node_modules/lifion-kinesis/node_modules/aws-sdk/lib/protocol/json.js:51:27)
at Request.callListeners (/app/node_modules/lifion-kinesis/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
at Request.emit (/app/node_modules/lifion-kinesis/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
at Request.emit (/app/node_modules/lifion-kinesis/node_modules/aws-sdk/lib/request.js:683:14)
at Request.transition (/app/node_modules/lifion-kinesis/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/app/node_modules/lifion-kinesis/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /app/node_modules/lifion-kinesis/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/app/node_modules/lifion-kinesis/node_modules/aws-sdk/lib/request.js:38:9)
at Request.<anonymous> (/app/node_modules/lifion-kinesis/node_modules/aws-sdk/lib/request.js:685:12)
at Request.callListeners (/app/node_modules/lifion-kinesis/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
```

I noticed that the call to [storeShardCheckpoint](https://github.com/lifion/lifion-kinesis/blob/develop/lib/state-store.js#L871) is not protected by the same `try/catch` as the other calls, which swallows `ConditionalCheckFailedException`. 

Note that we are running with `useEnhancedFanOut=true`.

Could this explain what we are seeing?

**Comment by eaviles** [comment]
Fixed in v1.4.0, now on npm (#751). `storeShardCheckpoint` now ignores `ConditionalCheckFailedException` like the other state writes, so a benign concurrent-write race no longer surfaces as an error (and no longer tears down the enhanced fan-out pipeline). Thanks for the report!
